included:
- TeamsChat

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

identifier_name:
    allowed_symbols: ["_"]
    validates_start_with_lowercase: false
    
line_length:
  warning: 180

opt_in_rules:
  - empty_collection_literal
#  unused_optional_binding

disabled_rules:
  - line_length
